### ISSUE TITLE
Items with ItemId 19607 and 19610 have incorrect tooltips.

### ISSUE THREAD

**Issue by MaxWayborn** [VanillaPlusTeam/bug-tracker#105]
**Description:**
Items with ItemId 19607 and 19610 have incorrect tooltips.

**Steps To Reproduce:**
1). Send the chat message: 
```
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffffff\124Hitem:19607:0:0:0\124h[ItemId 19607]\124h\124r and \124cffffffff\124Hitem:19610:0:0:0\124h[ItemId 19610]\124h\124r");
```
2). Click on these links in the chat to open the tooltip.

**Links:**
Item: [https://classic.wowhead.com/item=19607](https://classic.wowhead.com/item=19607)
Item: [https://classic.wowhead.com/item=19610](https://classic.wowhead.com/item=19610)

**Now tooltips look like this:**
![19607](https://github.com/VanillaPlusTeam/bug-tracker/assets/55049724/ea7dd368-b4d0-4eb4-bf44-f0e069ec792f) ![19610](https://github.com/VanillaPlusTeam/bug-tracker/assets/55049724/ecd18b70-4ceb-4625-af59-2a690805c25d)

**Comment by Fuku2222** [comment]
I think this is either intended, or just temporary, I don't think there is a ~+200 mana "green text"
