### ISSUE TITLE
Blade of Eternal Darkness

### ISSUE THREAD

**Issue by laciupacapra** [VanillaPlusTeam/bug-tracker#112]
The proc from https://www.wowhead.com/classic/item=17780/blade-of-eternal-darkness should proc off from a melee's hunters abilities (i've only tested it with hunter) and the enchantment Fiery Weapon and it doesn't. Please fix

**Comment by Trymv1** [comment]
Hunter abilities arent spells.

Fiery probably isnt.

Non-issue.

**Comment by Fuku2222** [comment]
I've never seen anyone claim/say this ever, on classic, vanilla//other pservers or otherwise. As stated above, hunter abilities are not spells - fiery is not a spell either.
