### ISSUE TITLE
warlock AC veteran trinket

### ISSUE THREAD

**Issue by GiveMeSignet** [VanillaPlusTeam/bug-tracker#125]
**Describe Your Issue**
Warlock AC veteran trinket doesn't work
**Steps To Reproduce**

1. que AC

2. wait eternity

3. equip trinket

**Comment by Fuku2222** [comment]
Wait - you know this trinket doesn't require AC to work (or shouldn't rather) right? Not sure why you even included "Q AC//wait" in steps.

Should be 
1) DoT anything without trinket and note GCD(s) (prob best to test with siphon life)
2) drop combat, swap trinkets
3) test again, compare GCD(s)
