### ISSUE TITLE
Pulsating Crystalline Shard/Robe of the Archmage relational behaviour

### ISSUE THREAD

**Issue by banqnmymatz** [VanillaPlusTeam/bug-tracker#126]
**Describe Your Issue**

After using Pulsating Crystalline Shard, it's not possible to use Robe of the Archmage and vise versa, because they share cooldown with each other. Only one of the items show cooldown (for ex. after using Pulsating Crystalline Shard, Robe of the Archmage seems usable but is not.)

**Steps To Reproduce**

1. Attain the two items "Pulsating Crystalline Shard" and "Robe of the Archmage" on the same character (it doesn't matter if equipped or in inventory)
2. Use one of the two said items
3. Try to use the other item. It will not show cooldown but is not usable

**Item:** https://classicdb.ch/?item=4743
https://classicdb.ch/?item=14152

**Expected Behavior**

Either the items shouldn't share cooldown with each other or both items should show cooldown.

**Comment by Fuku2222** [comment]
I noticed this with field duty papers/extra dimensional ghost revealer/ectoplasmic distiller too. Signing papers initiates CD on all of these items.
