### ISSUE TITLE
Paladin Unbreakable Talent not working

### ISSUE THREAD

**Issue by Thariuz** [VanillaPlusTeam/bug-tracker#127]
I was changing spec from ret to Prot when I noticed that the unbreakable talent giving 15% more HP is not working.  Tried Relogging in and Respec 3 times but talent still dont give the health bonus.

**Comment by Fuku2222** [comment]
Not a bug
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/9ab41d06-a68f-4b67-b78f-37fcbce562f5)

Update game and clear your WDB folder
