### ISSUE TITLE
Wushoolay's Charm of Spirits

### ISSUE THREAD

**Issue by Fuku2222** [VanillaPlusTeam/bug-tracker#129]
Item's cooldown is (extremely) bugged. Cooldown appears to be 3min, but it doesn't work after waiting ~3min. Relogging fixes bug - but it actually resets cooldown immediately. You can relog after using trinket instantly, log in and use again.

Acquire https://classicdb.ch/?item=19956
Equip
Use
Relog
Use again

**Comment by lutherening** [comment]
Already made a bug report for this. I would like to also add that the trinket ALSO BUGS OTHER ON USE TRINKETS, like AD exalted caster trinket Talisman of Ascendence, Strath UD trinket Ramstein's Lightning Bolts, CC exalted rep trinket Vial of Elune's Light and so forth. Please for the all that is good on azeroth, fix Shaman's ZG trinket: Wushoolay's Charm of Spirits !!!!

**Comment by Fuku2222** [comment]
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/f0b64709-739a-40e9-a61c-1ea639cbfcc7)

**Comment by Fuku2222** [comment]
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/eee51c09-9735-49f3-b557-55aba95d08d5)

**Comment by Fuku2222** [comment]
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/6a529869-f6b2-4ecc-9e01-99bc8198c2d0)

**Comment by Fuku2222** [comment]
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/1ba575f7-8548-4920-81f3-a79629942290)

**Comment by Fuku2222** [comment]
STILL FUCKING BROKEN
