### ISSUE TITLE
Shaman ZG trinket still bugged. My other report was cloed and will not be silenced untill it is fixed.

### ISSUE THREAD

**Issue by lutherening** [VanillaPlusTeam/bug-tracker#134]
1)Equip Wushoolay's Charm of Spirits
2)Use Wushoolay's Charm of Spirits
3)Wait 3min for cooldown to come off
4)After cooldown, no matter how long one waits the trinket will NOT be usable at ALL. Even switching trinkets will have no effct on the trinket.

A) I can post a video I uploaded on youtube trying to get the trinket to work if need be.

Item: https://www.wowhead.com/classic/item=19956/wushoolays-charm-of-spirits

**Comment by Vanillaplus** [comment]
The fix has already been applied to the dev branch.

**Comment by lutherening** [comment]
When will it apply? I just tried the trinket and it still wont work after using it once. I updated my game files and deleted cache and it still bugged. waited the 3 mins for it to come off cooldown and it still wont work.
