### ISSUE TITLE
Latest update changelog— 01/05/2024 00:14 mpq bugged

### ISSUE THREAD

**Issue by excogvplus** [VanillaPlusTeam/bug-tracker#138]
Hello there,

I run Wow client  (v+realmlist.wtf) under linux (debian based) using steam. So far all updates worked fine by deleting content of WDB folder and  copying in the latest patch-3.mpq in. With the newest this isn't the case: all tooltips (talents, bottom bars) remain the 'old tooltip' eg. warlock Mayhem has 5 minutes cooldown or priest Shadowform requires 560 mana to cast. However, those function as intended even tho I cannot cast Shadowform unless I have 560 mana. Addons follow what the 'old' tooltip shows.
I tried 3 times, with and without steam running, (never running v+ client) always the same result.
Any suggestions beside of reinstalling the client? It would be kind of lengthy considering the add-ons.
I have previously tried v+ client with the built-in update process but it takes ages to load even no update is coming up, so I would exclude this option.

**Comment by Pikelgeuse** [comment]
The patch was bugged for a day due to improper file list included in the mpq that was submitted to website. Fixed and closing ticket.
