### ISSUE TITLE
Pet not attacking out of sight

### ISSUE THREAD

**Issue by banqnmymatz** [VanillaPlusTeam/bug-tracker#140]
Since recent update, character pet is not attacking when it doesn't have "Line of Sight" on target

**Steps To Reproduce**
1. Target enemy unit behind wall or other LoS blocking geometry
2. Use Attack on pet bar
3. "Target is not in line of sight" error

**Expected Behavior**
Pets used to find their own path towards the target and run to attack them.

**Comment by Vanillaplus** [comment]
Not a bug, but a new feature, part of Arena PvP patch.
