### ISSUE TITLE
'Dark Pact' not returning 100% of mana

### ISSUE THREAD

**Issue by ghost** [VanillaPlusTeam/bug-tracker#25]
The Warlock spell 'Dark Pact' (Rank III) doesn't return 100% of the mana at the cost of 1200 of the minion's mana, but rather the other way around; almost all of the minion's mana is drained, while roughly 1200 is returned.

Also, in the spell description, the word 'pet' is used, but shouldn't that be 'minion'?

**Comment by Fuku2222** [comment]
No it scales. Also the wording is very intentional.
