### ISSUE TITLE
Typo in the talent calculator

### ISSUE THREAD

**Issue by chara-demon** [VanillaPlusTeam/bug-tracker#31]
1. Paladin Holy spec., Talent "Divine Intellect" - Increase "you" total intellect by x%. (your)
2. Paladin Holy spec., Talent "Improved Lay on Hands" - ...armor value from items "forx" seconds... (for x)
3. Paladin Holy spec., Talent "Searing Light" - Increase "you" Holy damage by x%. (your)
4. Paladin Holy spec., Talent "Consecration" - ...who "neter" the area. (enter?)

**Comment by Fuku2222** [comment]
The talent calculator is not maintained by V+ devs. Please contact Thirinena//Hawaiisa - this is a community maintained feature/page.
