### ISSUE TITLE
can't upgrade talent

### ISSUE THREAD

**Issue by Rottenn** [VanillaPlusTeam/bug-tracker#32]
While leveling a paladin, I ran into the fact that I could not level certain talents, namely consecration.  After resetting my talents, I can't level the Improved seal of Righteousness talent.
1.
2.
3.Improved seal of Righteousness, consecration
Spell: https://classic.wowhead.com/spell=26573/consecration
https://classic.wowhead.com/spell=20332/improved-seal-of-righteousness
I should be able to upgrade a talent if I have talent points.

**Comment by Fuku2222** [comment]
Install Patch-3.mpq and clear WDB folder
