### ISSUE TITLE
Quest: Don't Lose (Part Of) Your Head

### ISSUE THREAD

**Issue by Daemanis** [VanillaPlusTeam/bug-tracker#39]
Issue: Text is not written properly.
Picture:  please find attached a picture showing the incorrect text syntax
![image_2022-05-01_090430529](https://user-images.githubusercontent.com/94903782/166125414-0ad03f13-4688-4313-b65e-db55411ce02e.png)

**Comment by Fuku2222** [comment]
t-wow custom//community created quest.

"Oh, I lost my family, the plague took my home from me. On and on he goes! we get ! The plague took all of our homes and all of our families. But some of us at least came out of it with a jaw intact"

not sure what the 'extra' characters are for, but I'd imagine just an artifact from the original creation. The 'staff' did not create this quest
