### ISSUE TITLE
Ghost-o-plasm Round Up quest

### ISSUE THREAD

**Issue by Rafiky92** [VanillaPlusTeam/bug-tracker#49]
I can't pick up quest named Ghost-o-plasm Round Up at Desolace from NPC Hornizz Brimbuzzle. It has no prequests, nor reputation requiments. 

Steps To Reproduce
1. Go to Desolace (47,8 61,8)

Quest: https://classic.wowhead.com/quest=6134/ghost-o-plasm-round-up

Expected Behavior:
I should get the quest

**Comment by Fuku2222** [comment]
The area you are sent to for this quest has been massively changed. If you went there at appropriate level for this quest you would get 1 shot. SM is being revamped to end-game content and hence has had some relevant/related quest areas 'massaged'

**Comment by Fuku2222** [comment]
https://classicdb.ch/?npc=11560#comments
"Same location as Down The Scarlet Path quest line."
