### ISSUE TITLE
Joined AC 

### ISSUE THREAD

**Issue by Brncow** [VanillaPlusTeam/bug-tracker#54]
Joined up for ac with the .ac command while in Orgrimar inside of the bank and I zoned into the match but not in the proper location
I was in the air and could also see some NPCs also falling in the game.
Zoned back to my queue spot with deserter debuff

Steps to Reproduce
1. Join AC (.ac)

Should place players in the proper location of the starting area for respective faction

**Comment by Vanillaplus** [comment]
You should have an updated patch.3mpq
