### ISSUE TITLE
Morrowgrain turn-in bugged

### ISSUE THREAD

**Issue by spideylol** [VanillaPlusTeam/bug-tracker#55]
Hey,

Cannot turn in morrograin to Fandral Staghelm.

Steps to reproduce:
1 Acquire Morrowgrain
2 Attempt to turn in to Fandral

**Comment by Fuku2222** [comment]
You've done the pre-q(s)?

**Comment by Fuku2222** [comment]
wrong NPC, it's not staghelm who you end quest @
https://classicdb.ch/?npc=4217#ends:0-1+2
