### ISSUE TITLE
Faction Changing - Losing all flight paths

### ISSUE THREAD

**Issue by SambErr** [VanillaPlusTeam/bug-tracker#57]
Faction Changing - Losing all flight paths. 

To reproduce: Use a faction change

Another issue - When faction changing, you stay in your current place, so you log in to death. (The vendor is in SW/Org, Using the item at the vendor, will get you killed, I'd suggest a port to the others main city)

It's also an absolute pain to run from SW to Org, with no mount or flight paths (Because the mounts don't change when you do) or vica versa (Org to SW/IF)

**Comment by Vanillaplus** [comment]
Missing Flight Paths are not a bug.  Swapping SW/Org fixed.
