### ISSUE TITLE
Blazing Speed Haste bug

### ISSUE THREAD

**Issue by SambErr** [VanillaPlusTeam/bug-tracker#58]
https://www.youtube.com/watch?v=9up6u1hO5Sw

Video showing Blazing Speed doesn't work correctly - tooltip shows 50% haste, but it changes my fireball from 3.46 to 2.31 (33% instead of 50%) 

To reproduce - 
1. Be Mage - Have Blazing Speed Talent
2. Get it procced by being attacked
3. check cast speed of any spell 

![Untitled](https://user-images.githubusercontent.com/108256232/176124093-21d31473-c9a9-4588-9f53-cd37c6265394.jpg)

**Comment by SambErr** [comment]
Also doesn't increase how many missiles I shoot during arcane missiles.

**Comment by Trymv1** [comment]
Haste doesnt work the way you assume.

This is the formula: Base Spell / (1.00+Haste %) = Value
3.5 (fireball) / 1.5 (50% haste) = 2.33 cast.

Also Arcane Missiles dont *actually* work with Spell Haste, they're **specifically** coded to work with Time Pressure.

This is a non-issue.

**Comment by Fuku2222** [comment]
Yeah, haste doesn't affect channeled spells at all. I also got into this whole improper-scaling of haste thing myself about a year ago. It doesn't calculate based on YOUR cast time(s), but as Try said above, it's base-spell cast time.
