### ISSUE TITLE
Aspect of cheetah is broken: Dots give you daze. THEY SHOULD NOT

### ISSUE THREAD

**Issue by abrixD** [VanillaPlusTeam/bug-tracker#62]
Well known private server bug (even classic wow had it at the start)

Current situation: All magical debuffs (not only dots) give you daze UPON APPLICATION. And then, if it is a dot, each tick gives you daze again

Correct behaviour: Both non-damage magical debuffs AND Dots should NOT give you daze ever, whether upon application or when they do tick damage.

Proof:  PATCH 1.9  https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0
"Aspect of the Pack and Aspect of the Cheetah - Periodic damage will no longer trigger the Dazed effect."

Please, fix this as this is a major bug for hunters

**Comment by Fuku2222** [comment]
It's not a bug if it's intended
