### ISSUE TITLE
Paladin: [Retribution Aura] get no benefits from [Seal of the Crusader] and [Judgement of the Crusader]

### ISSUE THREAD

**Issue by ivan-rabtsevich** [VanillaPlusTeam/bug-tracker#63]
**Description**:

Paladin's [Retribution Aura] get no benefits from [Seal of the Crusader] and [Judgement of the Crusader].

**Steps To Reproduce**:

1. Enable [Retribution Aura];
2. Get hit from enemy and memorize damage caused by [Retribution Aura];
3. Use [Seal of the Crusader];
4. Get hit from enemy and memorize damage caused by [Retribution Aura];
5. Use [Seal of the Crusader];
6. Use [Judgement];
7. Get hit from enemy and memorize damage caused by [Retribution Aura];
8. Use [Seal of the Crusader];
9.  Get hit from enemy and memorize damage caused by [Retribution Aura];
10. Note that neither [Seal of the Crusader] nor [Judgement of the Crusader] does not affect on damage done by [Retribution Aura].

**Expected Behavior**:

[Seal of the Crusader] and [Judgement of the Crusader] increases damage done by [Retribution Aura] in the same way as it works with other holy effects like [Blessing of Sanctuary], [Consecration], [Holy Shield] etc.

**Comment by Trymv1** [comment]
Ret Aura has no Holy/Spell Damage scalings in Vanilla, thus is not affected.

Sanc/Cons/HolyShield *DO* have scalings.

Might be neat if it *did* scale, but this is a non-issue.

**Comment by Fuku2222** [comment]
Ret aura is a 'reflection' afaik - same as thorns, nagglering, etc.... As mentioned - these 'spells' don't have any scaling.
