### ISSUE TITLE
Paladin: [Redoubt] triggers even if shield is not equipped

### ISSUE THREAD

**Issue by ivan-rabtsevich** [VanillaPlusTeam/bug-tracker#66]
**Description**:

Paladin's [Redoubt] triggers even if shield is not equipped.

**Steps To Reproduce**:

1. Get [Redoubt] in talent tree;
2. Equip no shield;
3. Get aggroed by enemy mobs;
4. Note that [Redoubt] triggers even if shield is not equipped.

**Expected Behavior**:

[Redoubt] triggers only when shield is equipped.

**Comment by Trymv1** [comment]
Kinda moot since you cant block (beyond the 1% base) without a shield anyway.

Wars can Shield Block and remove the shield but keep the buff, and Shamans can have Earth Shield active even without wearing a shield. The blocks wont happen without a shield.

Non-issue?
