### ISSUE TITLE
Siphon Life damage / stack

### ISSUE THREAD

**Issue by Brncow** [VanillaPlusTeam/bug-tracker#67]
Siphon Life not dealing damage over two stacks on Moonkin in Winterspring (Owl Wing Thicket) , checked damage in other areas also It doesn't seem to be doing damage over two stacks on anything 

Steps To Reproduce

1. Go to Owl Wing Thicket
2. Cast Siphon Life twice on a moonkin - wait for damage to be delt
3. Cast Siphon Life a third time and check damage

Should be dealing increasing damage with each stack, but does not seem to increase after 2 stacks on this mob for some reason

**Comment by Fuku2222** [comment]
Working as intended (at least) as of now (probably earlier?)
