### ISSUE TITLE
Sayaad wings

### ISSUE THREAD

**Issue by Otari98** [VanillaPlusTeam/bug-tracker#69]
Sayaad wings often doesnt work when the ground in front of the character is not perfectly flat.
Steps To Reproduce

1. Equip sayaad wings
2.  Find a ramp or hill
3.  Use Sayaad wings
4.  Get disappointed

Expected Behavior
Sayaad wings should work like mage's blink.

**Comment by Fuku2222** [comment]
Have you compared it with mage's blink @ the same spot(s)?

**Comment by Otari98** [comment]
Yes, and they can blink easily where i can not.
