### ISSUE TITLE
Looting state stuck with despawning mobs

### ISSUE THREAD

**Issue by aapoalas** [VanillaPlusTeam/bug-tracker#74]
**Describe Your Issue**

When looting a mob, if the mob corpse despawns as you're looting your character will get stuck in a looting state.

The looting state cannot apparently be unstuck from the character by any easy means, as it does not seem to be removed with:
* spell casting
* moving
* leaving the area (leaving the zone not tested)
* looting other mobs (cannot loot other mobs while stuck in loot state already)
* timeout (at least few minutes)

**Steps To Reproduce**

1. In Western Plaguelands, at Dalson's Tears kill the zombie mobs that spawn two Rotting Worms on death.
2. Kill the Rotting Worms and wait approximately 30 seconds before looting (they despawn in approximately 30 seconds after death).
3. With good (or unlucky for player) timing the mob will despawn as looting is initiated.

**Mob:** https://classic.wowhead.com/npc=10925/rotting-worm

**Expected Behavior**
Getting stuck in looting state should not happen for these mobs, and in general for any mobs. I can imagine three ways to mitigate or fix the issue:

1. In Vanilla / Classic, these worms do not have a loot table and drop nothing. Thus their fast despawning is not an issue and the bug is mitigated.
2. Despawning a corpse should preferably interrupt / remove looting states targeting said corpse.
3. Looting should periodically (once every 10 or 30 seconds?) check if the conditions for looting are still valid: Corpse still exists, character is still close to the corpse etc.

**Comment by Fuku2222** [comment]
"looting state cannot apparently be unstuck from the character by any easy means"
Just relog. It happens when you're attempting to loot excess quest item(s) you already have as well. Relogging takes all of ~30 sec roughly. It's quite an easy fix.
If it does happen when looting quest item(s), you can also delete X and re-loot from mob(s) if it has yet to despawn - will also fix it if you can't//don't want to relog for whatever reason.

**Comment by aapoalas** [comment]
Yeah, relog does fix the issue but if you've ten mobs left to loot it's quite sad to have to relog and lose all the loot.
