### ISSUE TITLE
Wrath not affected by damage interruptions

### ISSUE THREAD

**Issue by Sesej55** [VanillaPlusTeam/bug-tracker#77]
I've been leveling a balance druid with zero points in the Nature's Focus talent. Wrath has not been noticeably affected at all from receiving damage which would cause a casting delay. Starfire however is affected normally. I'm not max level yet however this has been the situation with every level of wrath throughout the leveling process. It feels good this way, however I know that it shouldn't the the case.

**Comment by Beepde** [comment]
The tooltip for wrath reads "Cast can't be interrupted by damage, there is no bug here, it's intended
