### ISSUE TITLE
Enchant 20 arcane dmg doesn't work

### ISSUE THREAD

**Issue by bloomboom1** [VanillaPlusTeam/bug-tracker#78]
My tests show that "Enchant Gloves - Arcane Power" doesn't give any damage bonus to missiles
tests: https://discord.com/channels/530653671193706496/1043125995714121759/1043229635082735666

Steps To Reproduce
1 Put gloves on the mage with "Enchant Gloves - Arcane Power"
2 Put gloves on the mage without "Enchant Gloves - Arcane Power"
3 Damage does not change for "Arcane missiles"

**Comment by Fuku2222** [comment]
(30 mins ago these messages were posted)
![image](https://user-images.githubusercontent.com/34726033/230998689-1a2080f5-1d57-4f4c-a134-c503c5e0466d.png)
