### ISSUE TITLE
Talent Calculator linked in VPlusLauncher redirects to mcafee.com

### ISSUE THREAD

**Issue by abel503cl** [VanillaPlusTeam/bug-tracker#79]
This has been a very long standing issue I noticed a while ago. The Talent Calculator button doesn't work as intended, I think.

Steps to reproduce. 

Step 1. Open the VPlusLauncher

Step 2. Click on "Talent Calculator" button in the top right corner of the VPlusLauncher, which links to https://www.vanillaplus-talents.xyz/

Step 2.5. Link changes to http://1redird.com/r2.php?e=bXHevsWkLmDcFsFnqLY%2BbX49fmhsTm9tSGFUeTFJSnZtSGI3dVdqeTZETCsrak05Tlc4VjAyMko0MzdsK2RKY0lHeGwxenJVTzE5YWxyYVJ2eGtIMmJUdUgzNzBlMExlKzBzcUpoai9NV0tML0VqK0dpVTVIdWZSWFFINllYbFNsQTVjVUlUMG53aG43L1FHc3JQcCs2REFLd1k0czdGRHJzQ0VhTFQvYjUxMUlDVlFyOGQrMnhkYnZZemFIMSt5VUpWRDY2SnBTbWxrRm1QTUZqRG9nQ081RkR5RGRLRHFjOElaTEFXUThPV29Ba0kxUDFUY0FVQ3dEVXEzVURCNHB0MzNrS1U0Ny9XeC82WnJaMW5nWHdqNGFucnVqRnlSc3ZINkMrQ21TMTRtMERKZzQwTEJ4ZzNGaHNPUEJMZWFpNlRucmFlUVVmZFdsNnhRYjV1TDJlVU5PeTJTRHRwcU14bUc5c2RXQUl3eU16NndzZEV4ZzIzVWJDTjBEWUZIb2ZibVRZakgzR0ZBb3FVS3I5MTNOcmxMaGVnbDJUVDA2ZHJFb2FKdE15K0lWdktyNGpOQjRwKzZiOVprVzBrWU93TmpNWVFoMWprZCtwUmtxckc4dFFydzV3cjh6cGwvUUxLOFU5UkRpcVY4R1M0WVJwZGl5cVExejBoekF3MkZEOTZIUTlvWkhlamplNnhPdnlyZHJ1YjVhUWJtam9VbkdUN3JxTitjYVNDWjNUMkZiN21XSWpMWkdPK3ZuQUJvVVhualVHYnYzcGV1RThpWkVJSGhjR1pRM0VUL0tMWEFwZGJCalFwcU5uVzRteEJDYTFpVzhlWjhUa0NtMU1sdE9ZRFdpVi8yTWVOeEE1akFsVUloNDlhcnRaaGFsVVptelYrL0hiQVdsSVl3ZE9weDdPMTFObGx1bk0zUG1MdkFNR0dRSktxZ21Ed25rUzdmWWpTbStqUE5FbUFwTmVtUlhQMkVqSXduUnQwOUloK3hQSGlBM0dYd2FTQUNoUythcHpxOUdQOEF4VndJQm1ta25zNGNNWHlGbFc2NzhUSmlZUlF1bmVEU2ovdFByRjJoVXpCYXpwUVl6R3htK1lPaUZ2MkpOanhlR29pVjNwWFhucFFHZEhpVXg0MmpsYnJGaEVINVIwVmxmYlVYUEJ5b2hEcDN2Rk5yMVBOZVBLVlJKSlVnK3NSMjVGMEt2bVNiYUZTUXgybGxIajR0QXVSTXVucWtZNDUyWHNzaWhoZjF2NXgvazYyN3FVVmo2ND0%3D

Step 3. Get redirected to https://www.mcafee.com/?affId=62623&culture=en-us

Expected behavior. Get linked directly to working talent calculator https://hawaiisa.github.io/vanillaplus-talent-calculator/#/

**Comment by Vanillaplus** [comment]
It's outdated.
