### ISSUE TITLE
Talent Calculator in Launcher has Dead Link

### ISSUE THREAD

**Issue by dab2110** [VanillaPlusTeam/bug-tracker#8]
**Describe Your Issue**
Link to TALENT CALCULATOR on the launcher is dead.

**Steps To Reproduce**
Open Launcher, click TALENT CALCULATOR 

**Dead Link:** https://vanillaplus-talents.xyz/

**Working link:** https://hawaiisa.github.io/vanillaplus-talent-calculator/#/
(from website)

**Expected Behavior**
Link in Launcher to agree to link on the website

**Comment by Bluecoffeewow** [comment]
We get a new launcher, thanks.
Got one in test phase now.
