### ISSUE TITLE
Rockbiter scaling strength

### ISSUE THREAD

**Issue by VRR164** [VanillaPlusTeam/bug-tracker#85]
Describe Your Issue

The amount of strength given by rockbiter is much higher than the one on the tooltip and also seems to give more strength the more the shaman levels up.
For example here is my amount of strength on a level 60 shaman without rockbiter 
![No rockbiter](https://user-images.githubusercontent.com/124311846/216464403-dde9e3d5-c284-412c-bbc8-3766912874f0.PNG)
Here is my strength with rockbiter 7 
![Rockbiter 7 lvl60](https://user-images.githubusercontent.com/124311846/216464520-8c60d42d-a2b9-4d71-8743-de3622123c7a.PNG)
That's a 426 strength bonus much more than the 364 written on the tooltip
Steps To Reproduce

1.Get a shaman 
2.Use rockbiter (the rank used has to be the last ranked learned so not necessarily rank 7)
3.Level him up
4.Use rockbiter again

Expected Behavior

Rockbiter should give a flat amount of bonus strength and shouldn't give more the more you level up.

**Comment by Vanillaplus** [comment]
Not a bug. Per-level bonuses are not included in 1.12 UI. (+8 str per level = +48 str at lvl 60 w/o talents)
