### ISSUE TITLE
Some spells can go through Cloak of Shadows 

### ISSUE THREAD

**Issue by Tjeld** [VanillaPlusTeam/bug-tracker#86]
Warlocks can seduce with succubus and druids can apply faerie fire while cloak of shadows is active.

Steps to reproduce

1. Warlock sends succubus on rogue
2. Rogue uses cloak of shadows
3. Gets seduced anyway/druid applies faerie fire

Expected behavior
The cloak does its job.

**Comment by Fuku2222** [comment]
Faerie fire is intended to pass through many immunity effects. FF can even be applied to banished targets.
