### ISSUE TITLE
Warlock talents tree bug

### ISSUE THREAD

**Issue by bebboss** [VanillaPlusTeam/bug-tracker#88]
Hello, the talent "improved corruption" wasn't working on my Milhela. I've tried to click on it more then once but nothing happened. To see if the bug was for all the talents I've clicked on another one on the tree and it worked. Actually I didn't want to have a point on that talent but it was only for giving a try due to the previous bug. can you help? I wouldn't like to use my "free unlearn" only for that point. Thank you :)

**Comment by Fuku2222** [comment]
Please refrain from using this as troubleshooting. Refer to discord for support. This is bug-reporting.

However - update your patch-3 file by downloading from main website and place in your WoW's "Data" folder. Be sure to delete/clear your WDB folder too.

**Comment by Fuku2222** [comment]
see this closed ticket from someone else;
https://github.com/VanillaPlusTeam/bug-tracker/issues/83#issuecomment-1382665666
