### ISSUE TITLE
Flarecore Gloves

### ISSUE THREAD

**Issue by Beepde** [VanillaPlusTeam/bug-tracker#89]
Flarecore Gloves has an error with it's wording, but it isn't just an error as the mp5 isn't an "Equip:" effect either, I tested it and there's no mana gain at all. As you can see in the photo is functions as an actual activation item but when clicking the item nothing happens.
<img width="234" alt="Screen Shot 2023-04-05 at 5 02 23 PM" src="https://user-images.githubusercontent.com/109516864/230007258-152fef8e-c04b-465f-85a8-99648b51d528.png">

**Comment by Fuku2222** [comment]
Can confirm - no added MP5, not actually useable (doesn't apply any bonus). Item broken other than normal stats.
