### ISSUE TITLE
Spellstone not removing magic debuff

### ISSUE THREAD

**Issue by Fuku2222** [VanillaPlusTeam/bug-tracker#92]
Spellstone tooltip says "removes all harmful magic effects from the caster"

It does not remove this debuff ("Chains of Ice" from ghost(s) in DMW)

1. create/equip spellstone
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/ea7dfd2e-4944-4ab1-99cb-0a8bba8179db)
2. Get magic debuff(s) (Chains of Ice)
3. Use spellstone
4. Keep getting mana drained until debuff fades regardless of stone

**Comment by Fuku2222** [comment]
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/f422af2e-81c3-419d-a842-6c86f3f52ca8)
also not removing this debuff (it does disorient tho)

**Comment by Fuku2222** [comment]
didn't remove 
![image](https://github.com/VanillaPlusTeam/bug-tracker/assets/34726033/ec276ade-fabd-4e09-9f4c-73264f222220)
 just now either

**Comment by Vanillaplus** [comment]
You can not use it while out of control.

**Comment by Fuku2222** [comment]
> 
Chains of Ice and Withering Heat do not cause loss of control over character though. I noted in the 'despair' post that it is indeed a disorient and probably does not apply to this ticket (as Withering Heat//Chain(s) of Ice do)

**Comment by Trymv1** [comment]
Chains of Ice is a root, no? and there may be some ESL at large that technically includes it.

The Withering Heat is kinda sus tho, like it's already considering you 'stunned' because it has the stun code attached on the dispel.

**Comment by Fuku2222** [comment]
They are both still magic effects that do not CAUSE loss of control of character. You can still perform actions with either of these debuffs. They should both be removable with spellstone, no excuses. Ofc you should still get stunned from Withering Heat - but it should be dispellable.
