### ISSUE TITLE
Ankh of Life trinket is broken

### ISSUE THREAD

**Issue by Beepde** [VanillaPlusTeam/bug-tracker#95]
Steps To Reproduce
1. Equip Ankh of Life, note there is no 30 second equip cooldown
2. Attempt to use item (even after waiting 30 seconds)
3. Error message spell/item is not ready yet, the activate cannot be used

Item: https://www.wowhead.com/classic/item=1713/ankh-of-life

Expected Behavior
This is unquestionable broken, it appears that the coding isn't functioning as an on use item, due to it not having a cooldown when equipping.

https://github.com/VanillaPlusTeam/bug-tracker/assets/109516864/64d961e5-b757-4d84-8f7c-029d7525e767

https://github.com/VanillaPlusTeam/bug-tracker/assets/109516864/2337ff83-abfe-489f-9461-75f59cb04c89

**Comment by Beepde** [comment]
Update - It appears the trinket shares cooldown with this item, the lantern was on cooldown at the time of my previous videos, but there's no visual display to indicate a shared cooldown

https://github.com/VanillaPlusTeam/bug-tracker/assets/109516864/b33f827b-4168-4641-934f-6767c871c5d7

**Comment by Fuku2222** [comment]
> Update - It appears the trinket shares cooldown with this item, the lantern was on cooldown at the time of my previous videos, but there's no visual display to indicate a shared cooldown

close ticket//issue then :P
