### ISSUE TITLE
Lucifron adds

### ISSUE THREAD

**Issue by greentoilet** [VanillaPlusTeam/bug-tracker#99]
His 2 henchmen are immune to rip but not to other bleeds. 
What's the difference? Seems really wonky and out of place especially since this is not the case for other enemies of this archetype.

**Comment by Trymv1** [comment]
Is other bleeds Rend/Rupture or Rake specifically, as Rake wasnt classified as 'bleed' in vanilla and may not be here either despite the text change.

**Comment by greentoilet** [comment]
> Is other bleeds Rend/Rupture or Rake specifically, as Rake wasnt classified as 'bleed' in vanilla and may not be here either despite the text change.

I can only speak for Rake. 
Maybe a warrior can weigh in here? Does your Rend and Deep Wounds work on the Lucifron adds?
